### PR TITLE
Refuse to load Fabric mods on wrong side. Fixes #904.

### LINKED ISSUE #904: Dedicated server stop working with beta.39+bclib
### Mod Name

Bclib

### Mod Homepage

https://modrinth.com/mod/bclib

### Minecraft version

1.20.1

### Describe the bug

Dedicated server stop working with beta.39+bclib

### Steps to reproduce

1.update connector from beta.37 to beta.39
2.install forge server and bclib with connector
3.server freeze
...

### Logs

debug log: https://mclo.gs/JxVObeG

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by heipiao233**
## The Issue

Sinytra Connector loads some mods on the wrong side. This causes crash: #924 #904

## The Proposal

Refuse to load mods on the wrong side.

## Possible Side Effects

I don't think there is any possible side effects.

## Alternatives

#908, 2bc9aee. This solution doesn't fix the real problem.

## Additional Notes
No.

### CODE REVIEW

**Review by Su5eD — APPROVED** [review]

File: src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java [hunk 1]
```diff
@@ -289,7 +290,9 @@ private static List<JarTransformer.TransformableJar> handleDuplicateMods(List<Ja
             .toList();
     }
 
-    private static boolean shouldIgnoreMod(String id, Collection<String> loadedModIds) {
+    private static boolean shouldIgnoreMod(ConnectorLoaderModMetadata metadata, Collection<String> loadedModIds) {
+        if (!metadata.loadsInEnvironment(FabricLoader.getInstance().getEnvironmentType())) return false;
```
Comment (Su5eD) [inline src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java:294]: This should return `true` to stop a mod from loading in an incompatible environment

**Review by Su5eD — CHANGES_REQUESTED** [review]

**Comment by heipiao233** [comment]
Sorry for the wrong commit message. I'm ill.

File: src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java (hunk 1 above)
Comment (heipiao233) [reply src/main/java/dev/su5ed/sinytra/connector/locator/ConnectorLocator.java]: Ok.

**Review by Su5eD — APPROVED** [review]
